// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialRich.Entities;

namespace SocialRichAlejandro.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SocialRichAlejandro.Models.Networks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SNId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Networks");
                });

            modelBuilder.Entity("SocialRichAlejandro.Models.SocialNetwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("SocialNetwork");
                });

            modelBuilder.Entity("SocialRichAlejandro.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<int?>("SocialNetworkId");

                    b.Property<string>("Subname")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("SocialNetworkId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SocialRichAlejandro.Models.Users", b =>
                {
                    b.HasOne("SocialRichAlejandro.Models.SocialNetwork", "SocialNetwork")
                        .WithMany("User")
                        .HasForeignKey("SocialNetworkId");
                });
#pragma warning restore 612, 618
        }
    }
}
